# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-09-13 08:22
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djmoney.models.fields
import imagekit.models.fields
import store.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(blank=True, db_index=True, max_length=16, unique=True)),
                ('id', models.CharField(default=store.models.f, max_length=100, primary_key=True, serialize=False)),
                ('category_logo', imagekit.models.fields.ProcessedImageField(upload_to='images')),
                ('created', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('allowed_user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'indexes': [],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('maker', models.CharField(blank=True, db_index=True, max_length=32)),
                ('model', models.CharField(blank=True, db_index=True, max_length=32)),
                ('id', models.CharField(default=store.models.f, max_length=100, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('price_currency', djmoney.models.fields.CurrencyField(choices=[(b'BGN', 'Bulgarian Lev'), (b'EUR', 'Euro'), (b'USD', 'US Dollar')], default='BGN', editable=False, max_length=3)),
                ('price', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency=b'BGN', max_digits=10)),
                ('product_logo', imagekit.models.fields.ProcessedImageField(upload_to='images')),
                ('created', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Category')),
            ],
            options={
                'indexes': [],
            },
        ),
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('made_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('quantity', models.IntegerField(default=1, null=True)),
                ('address', models.CharField(max_length=200)),
                ('phonenumber', models.CharField(max_length=15)),
                ('delivered', models.BooleanField(default=False)),
                ('totalprice_currency', djmoney.models.fields.CurrencyField(choices=[(b'BGN', 'Bulgarian Lev'), (b'EUR', 'Euro'), (b'USD', 'US Dollar')], default='BGN', editable=False, max_length=3)),
                ('totalprice', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency=b'BGN', max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Product')),
                ('user', models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Purchases',
                'indexes': [],
            },
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set([('maker', 'model')]),
        ),
    ]
