# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-09-13 08:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchases',
            name='product',
        ),
        migrations.RemoveField(
            model_name='purchases',
            name='user',
        ),
        migrations.DeleteModel(
            name='Purchases',
        ),
    ]
