# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-09-15 11:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='makerid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Maker'),
        ),
    ]
