# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-08-12 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_logo',
            field=models.CharField(default=100, max_length=250),
            preserve_default=False,
        ),
    ]
