# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-09-13 08:35
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0002_auto_20160913_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('made_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('quantity', models.IntegerField(default=1, null=True)),
                ('address', models.CharField(max_length=200)),
                ('phonenumber', models.CharField(max_length=15)),
                ('delivered', models.BooleanField(default=False)),
                ('totalprice_currency', djmoney.models.fields.CurrencyField(choices=[(b'BGN', 'Bulgarian Lev'), (b'EUR', 'Euro'), (b'USD', 'US Dollar')], default='BGN', editable=False, max_length=3)),
                ('totalprice', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency=b'BGN', max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Product')),
                ('user', models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Purchases',
                'indexes': [],
            },
        ),
    ]
