# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-08-15 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category_category_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_logo',
            field=models.FileField(default=100, upload_to=b''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='category_logo',
            field=models.FileField(upload_to=b''),
        ),
    ]
