# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-08-15 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20160815_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_in_shopCart',
            field=models.BooleanField(default=False),
        ),
    ]
