# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-09-13 08:56
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_purchases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchases',
            name='totalprice',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('123'), default_currency=b'BGN', max_digits=10),
        ),
    ]
