# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-08-17 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20160816_0823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AlterField(
            model_name='category',
            name='category_logo',
            field=models.FileField(blank=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_logo',
            field=models.FileField(blank=True, upload_to=b''),
        ),
    ]
