# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-09-14 10:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0007_remove_userproducts_in_shop_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproducts',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Product', unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='userproducts',
            unique_together=set([('user', 'product')]),
        ),
    ]
