# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-08-17 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20160817_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
