# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-08-18 08:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20160818_0834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.AlterField(
            model_name='category',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 18, 8, 55, 23, 91307, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.CharField(default=b'2cb2ce855912c446', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 18, 8, 55, 23, 91359, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 18, 8, 55, 23, 101266, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.CharField(default=b'f1f5e93f3a56b440', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 18, 8, 55, 23, 101315, tzinfo=utc), editable=False),
        ),
    ]
