# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-08-19 13:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_auto_20160819_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 19, 13, 7, 42, 145928, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 19, 13, 7, 42, 145985, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 19, 13, 7, 42, 147617, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='maker',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='product',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 19, 13, 7, 42, 147671, tzinfo=utc), editable=False),
        ),
    ]
