# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-08-24 08:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_auto_20160824_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2016, 8, 24, 8, 59, 40, 856810, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 24, 8, 59, 40, 856888, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2016, 8, 24, 8, 59, 40, 858282, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 24, 8, 59, 40, 858338, tzinfo=utc), editable=False),
        ),
    ]
