# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-08-30 11:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_auto_20160826_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_logo',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2016, 8, 30, 11, 3, 30, 938901, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 30, 11, 3, 30, 938967, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2016, 8, 30, 11, 3, 30, 946866, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 30, 11, 3, 30, 946930, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_logo',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
    ]
