# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-09-01 07:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djmoney.models.fields
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0035_auto_20160830_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('made_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('count', models.IntegerField(default=1)),
            ],
            options={
                'indexes': [],
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_in_shopCart',
        ),
        migrations.AlterField(
            model_name='category',
            name='category_logo',
            field=imagekit.models.fields.ProcessedImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[(b'BGN', 'Bulgarian Lev'), (b'EUR', 'Euro'), (b'USD', 'US Dollar')], default='BGN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_logo',
            field=imagekit.models.fields.ProcessedImageField(upload_to='images'),
        ),
        migrations.AddField(
            model_name='payments',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Product'),
        ),
        migrations.AddField(
            model_name='payments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
