# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-09-01 11:42
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_auto_20160901_0758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='count',
            new_name='quantity',
        ),
        migrations.AddField(
            model_name='payments',
            name='address',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payments',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(default='1', max_length=128),
            preserve_default=False,
        ),
    ]
