# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-09-01 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_auto_20160901_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='phonenumber',
            field=models.CharField(max_length=15),
        ),
    ]
