# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-09-01 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_auto_20160901_1206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payments',
            options={'verbose_name_plural': 'Payments'},
        ),
        migrations.AddField(
            model_name='payments',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
