# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-09-02 08:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_auto_20160901_1402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchases',
            old_name='processed',
            new_name='delivered',
        ),
    ]
