# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-09-07 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0041_auto_20160902_0830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchases',
            name='product',
        ),
        migrations.AddField(
            model_name='purchases',
            name='product',
            field=models.ManyToManyField(to='store.Product'),
        ),
    ]
