# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-09-07 13:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0042_auto_20160907_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2016, 9, 7, 13, 29, 38, 530514, tzinfo=utc), editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 7, 13, 29, 38, 530626, tzinfo=utc), editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='made_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 7, 13, 29, 38, 533377, tzinfo=utc), editable=False),
        ),
        migrations.RemoveField(
            model_name='purchases',
            name='product',
        ),
        migrations.AddField(
            model_name='purchases',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='store.Product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchases',
            name='quantity',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
