# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-08-11 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_logo',
            field=models.CharField(default=20, max_length=1000),
            preserve_default=False,
        ),
    ]
